import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/child_profile.dart';
import '../models/milestone.dart';
import '../models/milestone_achievement.dart';
import '../data/milestones_data.dart';

class PdfExportService {
  PdfExportService._();

  static Future<void> exportMilestones({
    required ChildProfile profile,
    required List<MilestoneAchievement> achievements,
  }) async {
    final pdf = pw.Document(
      author: 'PlaySteps',
      title: '${profile.name} – Milestone Report',
    );

    // Group achievements by domain, sorted by age group
    final byDomain = <MilestoneDomain, List<_MilestoneRow>>{};
    for (final achievement in achievements) {
      final milestone = MilestonesData.all
          .where((m) => m.id == achievement.milestoneId)
          .firstOrNull;
      if (milestone != null) {
        byDomain
            .putIfAbsent(milestone.domain, () => [])
            .add(_MilestoneRow(milestone: milestone, achievement: achievement));
      }
    }
    for (final list in byDomain.values) {
      list.sort((a, b) =>
          a.milestone.ageGroupMonths.compareTo(b.milestone.ageGroupMonths));
    }

    final total = MilestonesData.all.length;
    final achieved = achievements.length;
    final pct = total == 0 ? 0 : (achieved / total * 100).round();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.symmetric(horizontal: 40, vertical: 36),
        header: (_) => _buildPageHeader(profile),
        footer: (_) => _buildPageFooter(),
        build: (_) => [
          pw.SizedBox(height: 24),
          _buildStatsBanner(achieved, total, pct),
          pw.SizedBox(height: 28),
          if (byDomain.isEmpty)
            pw.Center(
              child: pw.Text(
                'No milestones have been achieved yet.',
                style: pw.TextStyle(color: PdfColors.grey500, fontSize: 12),
              ),
            )
          else
            ...MilestoneDomain.values
                .where((d) => byDomain.containsKey(d))
                .map((d) => _buildDomainSection(d, byDomain[d]!)),
        ],
      ),
    );

    final filename =
        '${profile.name.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}_milestones_${DateFormat('yyyyMMdd').format(DateTime.now())}.pdf';
    await Printing.sharePdf(bytes: await pdf.save(), filename: filename);
  }

  // ─── Page-level widgets ───────────────────────────────────────────────────

  static pw.Widget _buildPageHeader(ChildProfile profile) {
    return pw.Column(
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.end,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'PlaySteps',
                  style: pw.TextStyle(
                    fontSize: 22,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.indigo700,
                  ),
                ),
                pw.Text(
                  'Developmental Milestone Report',
                  style: pw.TextStyle(fontSize: 11, color: PdfColors.grey600),
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  profile.name,
                  style: pw.TextStyle(
                      fontSize: 16, fontWeight: pw.FontWeight.bold),
                ),
                pw.Text(
                  profile.displayAge,
                  style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
                ),
                pw.Text(
                  'Generated ${DateFormat('MMMM d, yyyy').format(DateTime.now())}',
                  style: pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
                ),
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Divider(color: PdfColors.indigo200, thickness: 1.5),
      ],
    );
  }

  static pw.Widget _buildPageFooter() {
    return pw.Column(
      children: [
        pw.Divider(color: PdfColors.grey200),
        pw.Text(
          'Generated by PlaySteps · All data stored locally on your device · For discussion with your pediatrician',
          style: pw.TextStyle(fontSize: 7, color: PdfColors.grey400),
          textAlign: pw.TextAlign.center,
        ),
      ],
    );
  }

  // ─── Content widgets ──────────────────────────────────────────────────────

  static pw.Widget _buildStatsBanner(int achieved, int total, int pct) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColors.indigo50,
        borderRadius: pw.BorderRadius.circular(10),
        border: pw.Border.all(color: PdfColors.indigo100),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: [
          _statBox('$achieved', 'Achieved', PdfColors.green700),
          _statDivider(),
          _statBox('$total', 'Total', PdfColors.grey600),
          _statDivider(),
          _statBox('$pct%', 'Complete', PdfColors.indigo700),
        ],
      ),
    );
  }

  static pw.Widget _statBox(String value, String label, PdfColor color) {
    return pw.Column(
      children: [
        pw.Text(value,
            style: pw.TextStyle(
                fontSize: 26, fontWeight: pw.FontWeight.bold, color: color)),
        pw.Text(label,
            style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
      ],
    );
  }

  static pw.Widget _statDivider() =>
      pw.Container(width: 1, height: 40, color: PdfColors.indigo100);

  static pw.Widget _buildDomainSection(
      MilestoneDomain domain, List<_MilestoneRow> rows) {
    final domainColor = _domainPdfColor(domain);
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(height: 18),
        // Domain header
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 4),
          decoration: pw.BoxDecoration(
            color: domainColor,
            borderRadius: pw.BorderRadius.circular(6),
          ),
          child: pw.Text(
            domain.label.toUpperCase(),
            style: pw.TextStyle(
              fontSize: 9,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
              letterSpacing: 1.0,
            ),
          ),
        ),
        pw.SizedBox(height: 8),
        ...rows.map((row) => _buildMilestoneRow(row, domainColor)),
      ],
    );
  }

  static pw.Widget _buildMilestoneRow(_MilestoneRow row, PdfColor domainColor) {
    final dateStr =
        DateFormat('MMM d, yyyy').format(row.achievement.achievedDate);
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Colored left bar
          pw.Container(
            width: 3,
            height: 32,
            margin: const pw.EdgeInsets.only(right: 10, top: 2),
            decoration: pw.BoxDecoration(
              color: domainColor,
              borderRadius: pw.BorderRadius.circular(2),
            ),
          ),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Expanded(
                      child: pw.Text(
                        row.milestone.description,
                        style: pw.TextStyle(
                            fontSize: 10, fontWeight: pw.FontWeight.bold),
                      ),
                    ),
                    pw.SizedBox(width: 8),
                    pw.Text(
                      '${row.milestone.ageGroupMonths}m',
                      style:
                          pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
                    ),
                  ],
                ),
                pw.SizedBox(height: 2),
                pw.Row(children: [
                  pw.Container(
                    width: 8,
                    height: 8,
                    margin: const pw.EdgeInsets.only(right: 4),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.green600,
                      shape: pw.BoxShape.circle,
                    ),
                  ),
                  pw.Text(
                    'Achieved $dateStr',
                    style: pw.TextStyle(fontSize: 9, color: PdfColors.green800),
                  ),
                ]),
                if (row.achievement.notes?.isNotEmpty == true) ...[
                  pw.SizedBox(height: 2),
                  pw.Text(
                    '"${row.achievement.notes}"',
                    style: pw.TextStyle(
                      fontSize: 9,
                      color: PdfColors.grey600,
                      fontStyle: pw.FontStyle.italic,
                    ),
                  ),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }

  static PdfColor _domainPdfColor(MilestoneDomain domain) {
    switch (domain) {
      case MilestoneDomain.grossMotor:
        return PdfColors.blue600;
      case MilestoneDomain.fineMotor:
        return PdfColors.purple600;
      case MilestoneDomain.language:
        return PdfColors.cyan700;
      case MilestoneDomain.cognitive:
        return PdfColors.orange700;
      case MilestoneDomain.socialEmotional:
        return PdfColors.deepOrange600;
    }
  }
}

class _MilestoneRow {
  final Milestone milestone;
  final MilestoneAchievement achievement;
  const _MilestoneRow({required this.milestone, required this.achievement});
}
